### ISSUE TITLE
Abyssal obs trends comparison

### ISSUE THREAD

**Issue by adele157** [adele157/IAF-meltwater#13]
Compare to observed trends in abyssal temperature, salinity, oxygen.

**Comment by taimoorsohail** [comment]
OK, not sure what observational datasets we want to look at, but I've done a quick comparison with EN4. In general, the magnitude of change is about the same, and patterns of temp change seem to be closer than salinity change. EN4 includes ASBO, Argo, WOD and GTSPP data - not sure if that's all the data sources we are interested in. It is optimally interpolated, and it refers back to climatology in the absence of data (might be affecting the salinity data more than the temp.). 

The EN4 data is the 2009-2018 decadal mean minus the 1979-1988 decadal mean, while the model data is the 2009-2018 decadal mean temp + salinity Melt minus Control. Depth-averaged properties are calculated for all depths greater than 4000m. 

Purkey and Johnson (2010) present their data in terms of heat flux and thermal expansion which is an option to compare with....

![Abyssal_props_obs](https://user-images.githubusercontent.com/20695740/190328484-1c9d7cec-9de4-481b-a601-7a98a37fdb9d.png)

**Comment by taimoorsohail** [comment]
To do a basin-specific analysis I've made the following splits (I think @PaulSpence was talking about standardising basin definitions which would be great!

`if Ross_sector:
    lon_slice = slice(-215,-130)
if Weddell_sector:
    lon_slice = slice(-70,0)
if Australian_Antarctic_sector:
    lon_slice = slice(-280,-215)
if East_Antarctic_sector:
    lon_slice = slice(0,80)
    lon_slice_EN4 = slice(-360,-280)
if Amundsen_sector:
    lon_slice = slice(-130,-70)`

which looks like:

**Comment by taimoorsohail** [comment]
Based on feedback, I've done the same analysis from 90S - 60S: 

This is probably more relevant for an observational comparison @kathygunn.

![Basins_definitions](https://user-images.githubusercontent.com/20695740/206094339-9e5526a5-7364-499c-a852-0d1ef7ecd68f.png)

![T_S_anomaly_model](https://user-images.githubusercontent.com/20695740/206094335-c79fa044-6ee0-4896-8c6b-1aed0d07bf30.png)

![T_S_basins_model](https://user-images.githubusercontent.com/20695740/206094320-da2d8fb8-7897-4683-b8f9-fa560ab7240d.png)

**Comment by taimoorsohail** [comment]
Hi all, based on Kathy's salinity dataset (discussed in our meeting on 8/12/22) and this table from [Purkey et al, 2019](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2018JC014775) - the abyssal temperature and salinity change in this model is several orders of magnitude smaller than expected. So, we can assume the model forcing is not strong enough/compensating effects are too large. 

![Screenshot 2022-12-13 at 11 21 30 am](https://user-images.githubusercontent.com/20695740/207196789-a9ddbefd-3632-4457-94cd-9b511dbfea44.png)

I think we are safe to delete or archive the model outputs based on these results

**Comment by kathygunn** [comment]
Thank you for doing this final comparison

**Comment by adele-morrison** [comment]
Yes thanks Taimoor! I’m happy to delete. Though @matthew-england-unsw was wondering if we should hang on to them for a possible comparison with a future basal melt config comparison run. In which case we could delete the bgc and put the rest on massdata instead. Thoughts on this?

**Comment by matthew-england-unsw** [comment]
Yes — I think this could prove to be a useful control–like experiment to compare to the IAF run that has the increase in meltwater actually entering the ocean at depth.
