### ISSUE TITLE
Transports across 1000m isobath

### ISSUE THREAD

**Issue by matthew-england-unsw** [adele157/IAF-meltwater#3]

**Comment by matthew-england-unsw** [comment]
What is the response of the overturning cell off the shelf and in the abyss?
Does this line up with changes in the WMT rates?

**Comment by adele157** [comment]
Transports across the 1000m isobath too.

**Comment by schmidt-christina** [comment]
Circumpolar offshore transport across 1000-m isobath for meltwater run

![image](https://user-images.githubusercontent.com/38216156/190278867-480d048f-d75f-4e0b-a554-3cd071199562.png)

For the control run the necessary output wasn't saved.
